# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8221869a75fd6f369e94d0e80d6c6e6881788ed1d14100d7893bc5c98c0240fb1558cab769be5ce2c77c465a01fc9c6a3664c0acee89100eb7cb01859966d20

test:
  secret_key_base: 57181a90f2c60764be97fe79c0931990c47d88c1a1e84e2dce3ad150b18757d93c25c40f6b5fa78ef342ef8b78d5654346095f8ec03f3a805f9e88b5f4381444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
